# -*- coding: utf-8 -*-
"""vector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kos3tVYtMsAYxejlPrPCyUtO3fWIkcEb
"""

import numpy as np

a = np.array([3,4])
print(a)

type(a)

len(a)

a[0]

a[1]

b = np.array([7,2])
print(b)

print(a,b)

a + b

np.add(a,b)

a - b

a * b

np.multiply(a,b)

print(a)

np.dot(2,a)

print(a)
print(b)

np.dot(a,b)

print(a)

(3**2 + 4**2) **(1/2)

np.linalg.norm(a)

x = np.array([1,2,3])
np.linalg.norm(x)

import matplotlib.pyplot as plt

plt.quiver(3,4,angles='xy',scale_units='xy',scale=1)
plt.xlim(0,5)
plt.ylim(0,5)
plt.text(3,4,r'$\vec{u}$',size=25);

a = np.array([3,4])
b = np.array([7,2])
c = a + b

plt.quiver(a[0],a[1], angles='xy', scale_units='xy', scale=1)
plt.quiver(b[0],b[1], angles='xy', scale_units='xy', scale=1)
plt.quiver(c[0],c[1], angles='xy', scale_units='xy', scale=1, color='r')

plt.xlim(0,11)
plt.ylim(0,7)

plt.text(a[0],a[1],r'$\vec{A}$',size=15)
plt.text(b[0],b[1],r'$\vec{B}$',size=15);
plt.text(c[0],c[1],r'$\vec{C}$',size=15,c='r');

a = np.array([3,4])
b = np.array([7,2])
d = a - b

plt.quiver(a[0],a[1], angles='xy', scale_units='xy', scale=1)
plt.quiver(b[0],b[1], angles='xy', scale_units='xy', scale=1)
plt.quiver(d[0],d[1], angles='xy', scale_units='xy', scale=1, color='r')

plt.xlim(-5,9)
plt.ylim(-1,5)

plt.axvline(x=0 ,color='grey')
plt.axhline(y=0 ,color='grey')

plt.text(a[0],a[1],r'$\vec{A}$',size=15)
plt.text(b[0],b[1],r'$\vec{B}$',size=15);
plt.text(d[0],d[1],r'$\vec{D}$',size=15,c='r');



